Create RELEASE.md
canonical/alertmanager-operator pull request #11
Opened 2021-06-24 15:59 UTC by mmanciop

2021-06-27 00:22 UTC, dstathis requested changes

2021-06-27 00:22 UTC, dstathis commented on RELEASE.md
> +At any given time there are three revisions of the MySQL charm [available on CharmHub.io](https://charmhub.io/alertmanager-k8s), for each of the following channels:
MySQL should be alertmanager here

2021-06-28 07:57 UTC, balbirthomas approved these changes

2021-07-01 05:48 UTC, dstathis approved these changes

2021-07-01 09:30 UTC, balbirthomas approved these changes

2021-07-06 15:28 UTC, merged