Improve K8s service patching
canonical/alertmanager-operator pull request #28
Opened 2021-08-19 08:54 UTC by mmanciop

* Rename the `alertmanager-api` port to `alertmanager` for clarity, as the same `9093` port serves both UI and API
* Ensure K8s service is patched on charm upgrade

2021-08-19 09:00 UTC, jnsgruk approved these changes

2021-08-19 15:26 UTC, sed-i requested changes
As part of this change, can you please get rid of `_stored.k8s_service_patched`?
It seems that we only call it when it needs to be called anyway.
I originally had `k8s_service_patched` when I was calling the patch from within _common_exit_hook.

2021-08-20 07:55 UTC, jnsgruk approved these changes
Perhaps one day we could add some code to the patcher class that says "check if I'm patched" by just fetching the V1Service from the K8s api and comparing with one that we construct. That said, the current operation is fast, and would likely only result in a *very* short service disruption (likely in the ms range) - and only if someone issues an upgrade, which will restart alertmanager anyway...

2021-08-20 14:00 UTC, sed-i approved these changes

2021-08-20 14:01 UTC, merged